// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "TripMate support",
            "email": "tripmatesupport@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/users": {
            "post": {
                "description": "This endpoint creates a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Create User",
                "operationId": "create-user",
                "parameters": [
                    {
                        "description": "The data which this endpoint will use to create user",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/users_transport_http.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created user",
                        "schema": {
                            "$ref": "#/definitions/users_transport_http.CreateUserResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid user data",
                        "schema": {
                            "$ref": "#/definitions/core_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/core_http_response.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "core_http_response.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "full error text"
                },
                "message": {
                    "type": "string",
                    "example": "short human-readable message"
                }
            }
        },
        "users_transport_http.CreateUserRequest": {
            "type": "object",
            "required": [
                "birth_date",
                "email",
                "name",
                "password",
                "phone_number",
                "surname",
                "username"
            ],
            "properties": {
                "birth_date": {
                    "type": "string",
                    "example": "2006-01-02"
                },
                "description": {
                    "type": "string",
                    "maxLength": 1000,
                    "minLength": 1,
                    "example": "Some kind of description"
                },
                "email": {
                    "type": "string",
                    "example": "checkemail@gmail.com"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1,
                    "example": "Name"
                },
                "password": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 8,
                    "example": "some-random-password"
                },
                "phone_number": {
                    "type": "string",
                    "example": "+79990746978"
                },
                "surname": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1,
                    "example": "Surname"
                },
                "username": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1,
                    "example": "Username"
                }
            }
        },
        "users_transport_http.CreateUserResponse": {
            "type": "object",
            "properties": {
                "birth_date": {
                    "type": "string",
                    "example": "2006-01-02"
                },
                "created_at": {
                    "type": "string",
                    "example": "2006-01-02T15:06:07.292454Z"
                },
                "deleted_at": {
                    "type": "string",
                    "example": "2006-01-02T15:06:07.292454Z"
                },
                "description": {
                    "type": "string",
                    "example": "Some kind of description"
                },
                "email": {
                    "type": "string",
                    "example": "checkemail@gmail.com"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "Name"
                },
                "phone_number": {
                    "type": "string",
                    "example": "+79990746978"
                },
                "surname": {
                    "type": "string",
                    "example": "Surname"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2006-01-02T15:06:07.292454Z"
                },
                "username": {
                    "type": "string",
                    "example": "Username"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "TripMate API",
	Description:      "TripMate is the service that helps you plan your route and just travel\nwithout difficulties",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
