name: Lint

on:
  workflow_call:

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: ["services/app", "services/notification"]

    steps:
      - name: Checkout Go files
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: ${{ matrix.service }}/go.mod
          cache: true

      - name: fmt
        run: go fmt ./...
        working-directory: ${{ matrix.service }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12.2
          working-directory: ${{ matrix.service }}

      - name: Vet
        run: go vet ./...
        working-directory: ${{ matrix.service }}
